Poster page (posters clickable)
jocarino/test-hom-ui pull request #24
Opened 2023-04-23 17:12 UTC by goncalodasilva

2023-04-25 19:31 UTC, jocarino requested changes

2023-04-25 19:31 UTC, jocarino commented on src/poster/posterFeed.tsx
> +            localStorage.setItem('postersData', postersDataString);
shouldn't we be checking if the localstorage has something before calling the posters, and rendering the posters on that?

2023-04-25 19:31 UTC, jocarino commented on src/poster/posterPage.tsx
> +    name = name?.replace(':', '');
const routeParams = useParams();
const name = routeParams.name?.replace(':', '')
"var" is not a good practice in typescript -> also tried avoiding the .replace() but the trailling colon is kind of dumb, idk how to fix that atm, tried some stuff but couldn't figure it out

2023-04-26 07:01 UTC, goncalodasilva commented on src/poster/posterFeed.tsx
> +            localStorage.setItem('postersData', postersDataString);
maybe, but for now I don't think so, because that would imply adding a new functionality to reload manually. We can put it on the backlog though

2023-04-26 19:15 UTC, jocarino approved these changes

2023-04-26 19:15 UTC, merged